name_max_length: 25
gender_max_length: 15
birthday_min_length: 8
birthday_max_length: 20
address_max_length: 255
phone_number_min_length: 8
phone_number_max_length: 15
card_number_min_length: 10
card_number_max_length: 20
email_max_length: 255
password_min_length: 6
avatar_user_size: 80
